In [1]:
import numpy as np

In [2]:
a = np.random.rand(10) * 10 + 1
print('a________' + str(a))
np.floor(a)

a________[8.31530172 3.22291768 5.94980847 8.32257389 2.44335848 3.5295265
 9.16976869 8.41654121 1.0933301  4.63776758]


array([8., 3., 5., 8., 2., 3., 9., 8., 1., 4.])

In [3]:
a = np.arange(3 * 146).reshape(3,146)
for k in [0,1]:
	print(a[:,k * 64:(k + 1) * 64].shape)

(3, 64)
(3, 64)


In [4]:
a = np.zeros((3,2))
print(a)
np.zeros_like(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [2]:
a = np.arange(5)
print('square_-----' + str(np.square(a)))
print('power-----' + str(np.power(a,3)))
np.sqrt(a)

square_-----[ 0  1  4  9 16]
power-----[ 0  1  8 27 64]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])