In [1]:
import numpy as np

In [3]:
np.random.permutation(4)

array([2, 1, 0, 3])

In [4]:
np.random.permutation([1,2,34,6,7,4,2,6,7])

array([ 4,  2,  7,  6, 34,  1,  6,  2,  7])

In [10]:
a = np.arange(1,21).reshape(5,4)
np.random.seed(0)
print("a-----" + str(a))
np.random.permutation(a) 

a-----[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])